remedial2/remedialnfl/NFL/NFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

remedial2/remedialnfl/NFL/core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    #####C I U D A D E S
    path('create/ciudades/', views.CreateCiudades.as_view(), name="create_ciudades"),
    path('list/ciudades/', views.ListCiudades.as_view(), name="list_ciudades"),
    path('detail/ciudades/<int:pk>/', views.DetailCiudades.as_view(), name="detail_ciudades"),
    path('update/ciudades/<int:pk>/', views.UpdateCiudades.as_view(), name="update_ciudades"),
    path('delete/ciudades/<int:pk>/', views.DeleteCiudades.as_view(), name="delete_ciudades"),

    #### E Q U I P O S
    path('create/equipos/', views.CrearEquipo.as_view(), name="create_equipos"),
    path('list/equipos/', views.ListarEquipos.as_view(), name="list_equipos"),
    path('detail/equipos/<int:pk>/', views.DetalleEquipo.as_view(), name="detail_equipos"),
    path('update/equipos/<int:pk>/', views.ActualizarEquipo.as_view(), name="update_equipos"),
    path('delete/equipos/<int:pk>/', views.EliminarEquipo.as_view(), name="delete_equipos"),


    #### E S T  A D I O S
    path('create/estadios/', views.CrearEstadio.as_view(), name="create_estadios"),
    path('list/estadios/', views.ListarEstadios.as_view(), name="list_estadios"),
    path('detail/estadios/<int:pk>/', views.DetalleEstadio.as_view(), name="detail_estadios"),
    path('update/estadios/<int:pk>/', views.ActualizarEstadio.as_view(), name="update_estadios"),
    path('delete/estadios/<int:pk>/', views.EliminarEstadio.as_view(), name="delete_estadios"),


    #### P R O P P I E T A R I O S
    path('create/propietarios/', views.CrearPropietario.as_view(), name="create_propietarios"),
    path('list/propietarios/', views.ListarPropietarios.as_view(), name="list_propietarios"),
    path('detail/propietarios/<int:pk>/', views.DetallePropietario.as_view(), name="detail_propietarios"),
    path('update/propietarios/<int:pk>/', views.ActualizarPropietario.as_view(), name="update_propietarios"),
    path('delete/propietarios/<int:pk>/', views.EliminarPropietario.as_view(), name="delete_propietarios"),


    #### J U G A D O R E S
    path('create/jugadores/', views.CrearJugador.as_view(), name="create_jugadores"),
    path('list/jugadores/', views.ListarJugadores.as_view(), name="list_jugadores"),
    path('detail/jugadores/<int:pk>/', views.DetalleJugador.as_view(), name="detail_jugadores"),
    path('update/jugadores/<int:pk>/', views.ActualizarJugador.as_view(), name="update_jugadores"),
    path('delete/jugadores/<int:pk>/', views.EliminarJugador.as_view(), name="delete_jugadores"),


    ### P R O  E S T    
    path('create/propietario_estadios/', views.CrearPropietarioEstadio.as_view(), name="create_propietario_estadio"),
    path('list/propietario_estadios/', views.ListarPropietarioEstadios.as_view(), name="list_propietario_estadios"),
    path('detail/propietario_estadios/<int:pk>/', views.DetallePropietarioEstadio.as_view(), name="detail_propietario_estadio"),
    path('update/propietario_estadios/<int:pk>/', views.ActualizarPropietarioEstadio.as_view(), name="update_propietario_estadio"),
    path('delete/propietario_estadios/<int:pk>/', views.EliminarPropietarioEstadio.as_view(), name="delete_propietario_estadio"),

]

remedial2/remedialnfl/NFL/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Ciudades(models.Model):
    nombre = models.CharField(max_length=100)
    pais = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Estadios(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    capacidad = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre



class Propietarios(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)


    def __str__(self):
        return f"{self.nombre} {self.apellido}"


class Jugadores(models.Model):
    nombre = models.CharField(max_length=100)
    numero = models.IntegerField()
    posicion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Equipos(models.Model):
    nombre = models.CharField(max_length=100)
    liga = models.CharField(max_length=100)
    fundacion = models.DateField()
    ciudad = models.ForeignKey(Ciudades, on_delete=models.CASCADE)
    propietario = models.ForeignKey(Propietarios, on_delete=models.CASCADE, related_name='equipos_del_propietario')
    jugadores = models.ManyToManyField(Jugadores)

    def __str__(self):
        return self.nombre


class PropietariosEstadios(models.Model):
    propietario = models.OneToOneField(Propietarios, on_delete=models.CASCADE)
    estadio = models.OneToOneField(Estadios, on_delete=models.CASCADE)

    def __str__(self):
        return f"Estadio de {self.propietario.nombre} {self.propietario.apellido}: {self.estadio.nombre}"

remedial2/remedialnfl/NFL/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Ciudades, Estadios, Propietarios, Jugadores, Equipos, PropietariosEstadios
from .forms import (
    CiudadesForm, UpdateCiudadesForm, EquiposForm, UpdateEquiposForm,
    EstadiosForm, UpdateEstadiosForm, PropietariosForm, UpdatePropietariosForm,
    JugadoresForm, UpdateJugadoresForm, PropietariosEstadiosForm, UpdatePropietariosEstadiosForm,
)

# Views for Ciudades
class CreateCiudades(generic.CreateView):
    template_name = "core/ciudades/create_ciudades.html"
    model = Ciudades
    form_class = CiudadesForm
    success_url = reverse_lazy("core:list_ciudades")

class ListCiudades(generic.View):
    template_name = "core/ciudades/list_ciudades.html"
    context = {}

    def get(self, request, *args, **kwargs):
        ciudades = Ciudades.objects.all()
        self.context = {
            "ciudades": ciudades
        }
        return render(request, self.template_name, self.context)

class DetailCiudades(generic.View):
    template_name = "core/ciudades/detail_ciudades.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        ciudad = Ciudades.objects.get(pk=pk)
        self.context = {
            "ciudad": ciudad
        }
        return render(request, self.template_name, self.context)

class UpdateCiudades(generic.UpdateView):
    template_name = "core/ciudades/update_ciudades.html"
    model = Ciudades
    form_class = UpdateCiudadesForm
    success_url = reverse_lazy("core:list_ciudades")

class DeleteCiudades(generic.DeleteView):
    template_name = "core/ciudades/delete_ciudades.html"
    model = Ciudades
    success_url = reverse_lazy("core:list_ciudades")

# Views for Equipos
class CrearEquipo(generic.CreateView):
    template_name = "core/equipos/create_equipos.html"
    model = Equipos
    form_class = EquiposForm
    success_url = reverse_lazy("core:list_equipos")

class ListarEquipos(generic.View):
    template_name = "core/equipos/list_equipos.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipos = Equipos.objects.all()
        self.context = {
            "equipos": equipos
        }
        return render(request, self.template_name, self.context)

class DetalleEquipo(generic.View):
    template_name = "core/equipos/detail_equipos.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        equipo = Equipos.objects.get(pk=pk)
        self.context = {
            "equipo": equipo
        }
        return render(request, self.template_name, self.context)

class ActualizarEquipo(generic.UpdateView):
    template_name = "core/equipos/update_equipos.html"
    model = Equipos
    form_class = UpdateEquiposForm
    success_url = reverse_lazy("core:list_equipos")

class EliminarEquipo(generic.DeleteView):
    template_name = "core/equipos/delete_equipos.html"
    model = Equipos
    success_url = reverse_lazy("core:list_equipos")

# Views for Estadios
class CrearEstadio(generic.CreateView):
    template_name = "core/estadios/create_estadios.html"
    model = Estadios
    form_class = EstadiosForm
    success_url = reverse_lazy("core:list_estadios")

class ListarEstadios(generic.View):
    template_name = "core/estadios/list_estadios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        estadios = Estadios.objects.all()
        self.context = {
            "estadios": estadios
        }
        return render(request, self.template_name, self.context)

class DetalleEstadio(generic.View):
    template_name = "core/estadios/detail_estadios.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        estadio = Estadios.objects.get(pk=pk)
        self.context = {
            "estadio": estadio
        }
        return render(request, self.template_name, self.context)

class ActualizarEstadio(generic.UpdateView):
    template_name = "core/estadios/update_estadios.html"
    model = Estadios
    form_class = UpdateEstadiosForm
    success_url = reverse_lazy("core:list_estadios")

class EliminarEstadio(generic.DeleteView):
    template_name = "core/estadios/delete_estadios.html"
    model = Estadios
    success_url = reverse_lazy("core:list_estadios")

# Views for Propietarios
class CrearPropietario(generic.CreateView):
    template_name = "core/propietarios/create_propietarios.html"
    model = Propietarios
    form_class = PropietariosForm
    success_url = reverse_lazy("core:list_propietarios")

class ListarPropietarios(generic.View):
    template_name = "core/propietarios/list_propietarios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        propietarios = Propietarios.objects.all()
        self.context = {
            "propietarios": propietarios
        }
        return render(request, "core/propietarios/list_propietarios.html", self.context)

class DetallePropietario(generic.View):
    template_name = "core/propietarios/detail_propietarios.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        propietario = Propietarios.objects.get(pk=pk)
        self.context = {
            "propietario": propietario
        }
        return render(request, "core/propietarios/detail_propietarios.html", self.context)

class ActualizarPropietario(generic.UpdateView):
    template_name = "core/propietarios/update_propietarios.html"
    model = Propietarios
    form_class = UpdatePropietariosForm
    success_url = reverse_lazy("core:list_propietarios")

class EliminarPropietario(generic.DeleteView):
    template_name = "core/propietarios/delete_propietarios.html"
    model = Propietarios
    success_url = reverse_lazy("core:list_propietarios")

# Views for Jugadores
class CrearJugador(generic.CreateView):
    template_name = "core/jugadores/create_jugadores.html"
    model = Jugadores
    form_class = JugadoresForm
    success_url = reverse_lazy("core:list_jugadores")

class ListarJugadores(generic.View):
    template_name = "core/jugadores/list_jugadores.html"
    context = {}

    def get(self, request, *args, **kwargs):
        jugadores = Jugadores.objects.all()
        self.context = {
            "jugadores": jugadores
        }
        return render(request, "core/jugadores/list_jugadores.html", self.context)

class DetalleJugador(generic.View):
    template_name = "core/jugadores/detail_jugadores.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        jugador = Jugadores.objects.get(pk=pk)
        self.context = {
            "jugador": jugador
        }
        return render(request, "core/jugadores/detail_jugadores.html", self.context)

class ActualizarJugador(generic.UpdateView):
    template_name = "core/jugadores/update_jugadores.html"
    model = Jugadores
    form_class = UpdateJugadoresForm
    success_url = reverse_lazy("core:list_jugadores")

class EliminarJugador(generic.DeleteView):
    template_name = "core/jugadores/delete_jugadores.html"
    model = Jugadores
    success_url = reverse_lazy("core:list_jugadores")


# Views for PropietariosEstadios
class CrearPropietarioEstadio(generic.CreateView):
    template_name = "core/propiest/create_propietario_estadio.html"
    model = PropietariosEstadios
    form_class = PropietariosEstadiosForm
    success_url = reverse_lazy("core:list_propietario_estadios")

class ListarPropietarioEstadios(generic.View):
    template_name = "core/propiest/list_propietario_estadios.html"
    context = {}

    def get(self, request, *args, **kwargs):
        propietarios_estadios = PropietariosEstadios.objects.all()
        self.context = {
            "propietarios_estadios": propietarios_estadios
        }
        return render(request, "core/propiest/list_propietario_estadios.html", self.context)

class DetallePropietarioEstadio(generic.View):
    template_name = "core/propiest/detail_propietario_estadio.html"
    context = {}

    def get(self, request, pk, *args, **kwargs):
        propietario_estadio = PropietariosEstadios.objects.get(pk=pk)
        self.context = {
            "propietario_estadio": propietario_estadio
        }
        return render(request, "core/propiest/detail_propietario_estadios.html", self.context)

class ActualizarPropietarioEstadio(generic.UpdateView):
    template_name = "core/propiest/update_propietario_estadio.html"
    model = PropietariosEstadios
    form_class = UpdatePropietariosEstadiosForm
    success_url = reverse_lazy("core:list_propietario_estadios")

class EliminarPropietarioEstadio(generic.DeleteView):
    template_name = "core/propiest/delete_propietario_estadio.html"
    model = PropietariosEstadios
    success_url = reverse_lazy("core:list_propietario_estadios")

remedial2/remedialnfl/NFL/templates/core/equipos/create_equipos.html
{% extends "base/base.html" %}

{% block title %}
  CREAR VISTA DE EQUIPO
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" style="margin: 100px; color: rgb(0, 17, 112);">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control" style="background-color: rgb(0, 70, 0); color: rgb(255, 255, 255);">Crear Equipo </button>
        <br>
        <a href="{% url 'core:list_equipos' %}" class="btn btn-outline-warning form-control" style="background-color: rgb(172, 187, 0); color: rgb(255, 255, 255);" >Cancelar</a>
    </form>
{% endblock content %}

remedial2/remedialnfl/NFL/templates/core/equipos/delete_equipos.html
{% extends "base/base.html" %}

{% block title %}
ELIMINAR VISTA DE EQUIPO
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">   Eliminar Equipo</div>
            <div class="card-body">
              <h4 class="card-title">{{ object.equipo_name }}</h4>
              <p>¿Realmente deseas eliminar este equipo?</p>
              <button type="submit" class="btn btn-danger">Eliminar Equipo</button>
              <a href="{% url 'core:list_equipos' %}" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        
        
        
    </form>
{% endblock content %}  

remedial2/remedialnfl/NFL/templates/core/equipos/detail_equipos.html
{% extends "base/base.html" %}

{% block title %}
VISTA DETALLADA DE EQUIPO
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                {{ equipo }}
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <strong>Este es el equipo: {{ equipo.nombre }}.</strong> Son de la liga {{ equipo.liga }}, Fundación de la liga: {{ equipo.fundacion }}.
                {% if equipo.ciudad %}
                    Son de la ciudad {{ equipo.ciudad }}.
                {% endif %}
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Detalles
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <a href="{% url 'core:list_equipos' %}" class="btn btn-link">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

remedial2/remedialnfl/NFL/templates/core/equipos/list_equipos.html
{% extends "base/base.html" %}

{% block title %}
VER LISTA EQUIPO
{% endblock title %}

{% block content %}
<br>
<hr>
    <a href="{% url 'core:create_equipos' %}" class="btn btn-outline-success form-control">Crear un nuevo equipo</a>
    <table class="table table-striped table-hover">
        <thead>
            <th style="background-color: black; color: white; text-align: center;">ID</th>
            <th style="background-color: black; color: white; text-align: center;">NOMBRE DEL EQUIPO</th>
            <th style="background-color: black; color: white; text-align: center;">LIGA</th>
            <th style="background-color: black; color: white; text-align: center;">FUNDACIÓN</th>
            <th style="background-color: black; color: white; text-align: center;">PROPIETARIO</th>
            <th style="background-color: black; color: white; text-align: center;">JUGADORES</th>
            <th style="background-color: black; color: white; text-align: center;">ACCIONES</th>
        </thead>
        <tbody>
            {% for equipo in equipos %}
                <tr>
                    <td style="background-color: black; color: white; text-align: center;">{{ equipo.id }}</td>
                    <td style="background-color: gray;">{{ equipo.nombre }}</td>
                    <td style="background-color: rgb(186, 186, 186); text-align: center;">{{ equipo.liga }}</td>
                    <td style="background-color: rgb(214, 211, 211); text-align: center;">{{ equipo.fundacion|date:"Y-m-d" }}</td>
                    <td style="background-color: rgb(214, 211, 211); text-align: center;">{{ equipo.propietario.nombre }} {{ equipo.propietario.apellido }}</td>
                    <td style="background-color: rgb(214, 211, 211); text-align: center;">
                        {% for jugador in equipo.jugadores.all %}
                            {{ jugador.nombre }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td style="text-align: center;"><a href="{% url 'core:detail_equipos' equipo.id %}" class="btn btn-outline-info">Detalle</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:update_equipos' equipo.id %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td style="text-align: center;"><a href="{% url 'core:delete_equipos' equipo.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

remedial2/remedialnfl/NFL/templates/core/equipos/update_equipos.html
{% extends "base/base.html" %}

{% block title %}
  ACTUALIZAR VISTA DE EQUIPOS
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Actualizar Equipo</button>
        <br>
        <a href="{% url 'core:list_equipos' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}